// Fallback data for API when database is not available
export const sampleProducts = [
  {
    _id: '1',
    name: 'Luxury Gradient Candles',
    title: 'Luxury Gradient Candles',
    description: 'Elegant ombre candles with beautiful red-to-white gradient. Perfect for romantic dinners and special occasions.',
    price: 45.99,
    originalPrice: 55.99,
    discount: 18,
    imageUrl: '/images/candles/candle-collection-2.png',
    category: 'Scented Candles',
    stock: 15,
    status: 'bestseller',
    features: ['Hand-dipped gradient', 'Premium wax blend', 'Romantic ambiance', 'Long burn time'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '2',
    name: 'Vanilla Spice Warmth',
    title: 'Vanilla Spice Warmth',
    description: 'Warm and inviting vanilla spice candles that fill your space with cozy comfort. Perfect for autumn and winter evenings.',
    price: 38.99,
    originalPrice: 47.99,
    discount: 19,
    imageUrl: '/images/candles/candle-collection-3.png',
    category: 'Scented Candles',
    stock: 30,
    status: 'featured',
    features: ['Vanilla spice blend', 'Cozy atmosphere', 'Premium wax', 'Long-lasting'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '3',
    name: 'Citrus Burst Energy',
    title: 'Citrus Burst Energy',
    description: 'Energizing citrus candles that invigorate your senses and brighten your day with zesty orange and lemon notes.',
    price: 41.99,
    originalPrice: 51.99,
    discount: 19,
    imageUrl: '/images/candles/candle-collection-4.png',
    category: 'Scented Candles',
    stock: 28,
    status: 'new',
    features: ['Citrus blend', 'Energizing scent', 'Mood lifting', 'Bright colors'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '4',
    name: 'Premium Gift Box',
    title: 'Premium Gift Box',
    description: 'Elegant gift box containing a curated selection of premium items. Perfect for birthdays, anniversaries, and special occasions.',
    price: 65.00,
    originalPrice: 80.00,
    discount: 19,
    imageUrl: '/images/candles/candle-collection-9.jpg',
    category: 'Gift Sets',
    stock: 15,
    status: 'featured',
    features: ['Curated selection', 'Premium packaging', 'Special occasions', 'Elegant presentation'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '5',
    name: 'French Lavender Elegance',
    title: 'French Lavender Elegance',
    description: 'Premium French lavender scented candles with sophisticated floral notes. Creates a serene and calming atmosphere.',
    price: 48.99,
    originalPrice: 58.99,
    discount: 17,
    imageUrl: '/images/candles/candle-collection-5.png',
    category: 'Scented Candles',
    stock: 22,
    status: 'bestseller',
    features: ['French lavender', 'Sophisticated scent', 'Calming atmosphere', 'Premium quality'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  }
];