// Fallback data for API when database is not available
export const sampleProducts = [
  {
    _id: '1',
    name: 'Luxury Gradient Candles',
    title: 'Luxury Gradient Candles',
    description: 'Elegant ombre candles with beautiful red-to-white gradient. Perfect for romantic dinners and special occasions.',
    price: 45.99,
    originalPrice: 55.99,
    discount: 18,
    imageUrl: '/images/candles/candle-collection-2.png',
    category: 'Scented Candles',
    stock: 15,
    status: 'bestseller',
    features: ['Hand-dipped gradient', 'Premium wax blend', 'Romantic ambiance', 'Long burn time'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '2',
    name: 'Vanilla Spice Warmth',
    title: 'Vanilla Spice Warmth',
    description: 'Warm and inviting vanilla spice candles that fill your space with cozy comfort. Perfect for autumn and winter evenings.',
    price: 38.99,
    originalPrice: 47.99,
    discount: 19,
    imageUrl: '/images/candles/candle-collection-3.png',
    category: 'Scented Candles',
    stock: 30,
    status: 'featured',
    features: ['Vanilla spice blend', 'Cozy atmosphere', 'Premium wax', 'Long-lasting'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '3',
    name: 'Citrus Burst Energy',
    title: 'Citrus Burst Energy',
    description: 'Energizing citrus candles that invigorate your senses and brighten your day with zesty orange and lemon notes.',
    price: 41.99,
    originalPrice: 51.99,
    discount: 19,
    imageUrl: '/images/candles/candle-collection-4.png',
    category: 'Scented Candles',
    stock: 28,
    status: 'new',
    features: ['Citrus blend', 'Energizing scent', 'Mood lifting', 'Bright colors'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '4',
    name: 'Premium Gift Box',
    title: 'Premium Gift Box',
    description: 'Elegant gift box containing a curated selection of premium items. Perfect for birthdays, anniversaries, and special occasions.',
    price: 65.00,
    originalPrice: 80.00,
    discount: 19,
    imageUrl: '/images/candles/candle-collection-9.jpg',
    category: 'Gift Sets',
    stock: 15,
    status: 'featured',
    features: ['Curated selection', 'Premium packaging', 'Special occasions', 'Elegant presentation'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '5',
    name: 'French Lavender Elegance',
    title: 'French Lavender Elegance',
    description: 'Premium French lavender scented candles with sophisticated floral notes. Creates a serene and calming atmosphere.',
    price: 48.99,
    originalPrice: 58.99,
    discount: 17,
    imageUrl: '/images/candles/candle-collection-5.png',
    category: 'Scented Candles',
    stock: 22,
    status: 'bestseller',
    features: ['French lavender', 'Sophisticated scent', 'Calming atmosphere', 'Premium quality'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '6',
    name: 'Ocean Breeze Serenity',
    title: 'Ocean Breeze Serenity',
    description: 'Fresh ocean-inspired candles with crisp marine notes that transport you to coastal shores and peaceful waves.',
    price: 42.99,
    originalPrice: 52.99,
    discount: 19,
    imageUrl: '/images/candles/candle-collection-6.jpg',
    category: 'Scented Candles',
    stock: 25,
    status: 'featured',
    features: ['Ocean breeze scent', 'Marine notes', 'Coastal vibes', 'Refreshing aroma'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '7',
    name: 'Warm Amber Glow',
    title: 'Warm Amber Glow',
    description: 'Rich amber-scented candles with warm, golden notes perfect for creating an intimate and cozy atmosphere.',
    price: 39.99,
    originalPrice: 49.99,
    discount: 20,
    imageUrl: '/images/candles/candle-collection-7.jpg',
    category: 'Scented Candles',
    stock: 18,
    status: 'bestseller',
    features: ['Warm amber', 'Golden glow', 'Intimate atmosphere', 'Rich fragrance'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '8',
    name: 'Kids Creative Art Set',
    title: 'Kids Creative Art Set',
    description: 'Complete art and stationery set for children including colorful markers, crayons, and creative activity books.',
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    imageUrl: '/images/kids-stationery.png',
    category: 'Kids Stationery',
    stock: 35,
    status: 'featured',
    features: ['Complete art set', 'Child-safe materials', 'Educational activities', 'Creative development'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '9',
    name: 'Rose Garden Romance',
    title: 'Rose Garden Romance',
    description: 'Luxurious rose-scented candles with delicate floral notes, perfect for romantic occasions and elegant spaces.',
    price: 52.99,
    originalPrice: 62.99,
    discount: 16,
    imageUrl: '/images/candles/candle-collection-8.jpg',
    category: 'Scented Candles',
    stock: 20,
    status: 'bestseller',
    features: ['Rose garden scent', 'Romantic ambiance', 'Elegant design', 'Long-lasting fragrance'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '10',
    name: 'Premium Notebook Collection',
    title: 'Premium Notebook Collection',
    description: 'Set of beautifully designed notebooks with quality paper, perfect for journaling, note-taking, and creative writing.',
    price: 24.99,
    originalPrice: 34.99,
    discount: 29,
    imageUrl: '/images/categories/kids-stationery.jpg',
    category: 'Kids Stationery',
    stock: 40,
    status: 'featured',
    features: ['High-quality paper', 'Beautiful designs', 'Multiple sizes', 'Durable binding'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '11',
    name: 'Sacred Prayer Candle Set',
    title: 'Sacred Prayer Candle Set',
    description: 'Elegant religious candles designed for prayer and meditation, creating a peaceful and spiritual atmosphere.',
    price: 35.99,
    originalPrice: 45.99,
    discount: 22,
    imageUrl: '/images/categories/religious-products.jpg',
    category: 'Religious Products',
    stock: 30,
    status: 'trending',
    features: ['Sacred design', 'Long burn time', 'Peaceful atmosphere', 'Spiritual ambiance'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: '12',
    name: 'Celebration Gift Bundle',
    title: 'Celebration Gift Bundle',
    description: 'Special occasion gift bundle featuring a curated selection of candles, stationery, and decorative items.',
    price: 75.99,
    originalPrice: 95.99,
    discount: 21,
    imageUrl: '/images/categories/gifts.jpg',
    category: 'Gift Sets',
    stock: 12,
    status: 'featured',
    features: ['Curated selection', 'Perfect for celebrations', 'Beautiful packaging', 'Multiple items included'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  }
];